import { useState, useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Search, X, Download } from 'lucide-react';

interface AppItem {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  default: boolean;
  features: string[];
  rating: number;
  downloads: string;
}

const APPS_DATABASE: AppItem[] = [
  // Core Apps
  {
    id: 'mintmobile',
    name: 'MintMobile',
    category: 'Core',
    description: 'Commercial For Phone Service',
    icon: '📱',
    default: true,
    features: ['Phone plans', 'Coverage maps', 'Account management', 'Billing'],
    rating: 4.5,
    downloads: '2.5M',
  },
  {
    id: 'church',
    name: 'Church',
    category: 'Core',
    description: 'Sunday & Wednesday Worship, Teacher, Group, Prayer Meeting',
    icon: '⛪',
    default: true,
    features: ['Service schedules', 'Prayer groups', 'Sermons', 'Community events'],
    rating: 4.8,
    downloads: '1.2M',
  },
  {
    id: 'trending',
    name: 'Trending',
    category: 'Core',
    description: "What's going places",
    icon: '🔥',
    default: true,
    features: ['Trending topics', 'Real-time updates', 'Hashtag tracking', 'Viral content'],
    rating: 4.3,
    downloads: '3.1M',
  },

  // Professional Apps
  {
    id: 'website-builder',
    name: 'Website Builder',
    category: 'Professional',
    description: 'Create and publish your own websites',
    icon: '🌐',
    default: false,
    features: ['Drag & drop editor', 'Templates', 'Domain management', 'Analytics', 'SEO tools'],
    rating: 4.6,
    downloads: '890K',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'Professional',
    description: 'A command-line interface for the desktop',
    icon: '⌨️',
    default: true,
    features: ['Command execution', 'File management', 'Script running', 'System info'],
    rating: 4.7,
    downloads: '1.5M',
  },
  {
    id: 'files',
    name: 'Files',
    category: 'Professional',
    description: 'A comprehensive file explorer for all user data',
    icon: '📁',
    default: true,
    features: ['File browsing', 'Search', 'Favorites', 'Quick access', 'Sharing'],
    rating: 4.8,
    downloads: '5.2M',
  },
  {
    id: 'contracts',
    name: 'Contracts',
    category: 'Professional',
    description: 'Manage and view contracts',
    icon: '📋',
    default: false,
    features: ['Contract storage', 'Version control', 'Signing', 'Expiry alerts'],
    rating: 4.4,
    downloads: '340K',
  },
  {
    id: 'browser',
    name: 'Browser',
    category: 'Professional',
    description: 'A web browser to navigate the internet',
    icon: '🌍',
    default: true,
    features: ['Web browsing', 'Tabs', 'History', 'Bookmarks', 'Extensions'],
    rating: 4.7,
    downloads: '8.9M',
  },
  {
    id: 'bookmarks',
    name: 'Bookmarks',
    category: 'Professional',
    description: 'Manage your web bookmarks',
    icon: '🔖',
    default: true,
    features: ['Save bookmarks', 'Collections', 'Sync', 'Search', 'Tags'],
    rating: 4.5,
    downloads: '1.8M',
  },
  {
    id: 'post-app',
    name: 'Post',
    category: 'Professional',
    description: 'Create and edit posts',
    icon: '✍️',
    default: false,
    features: ['Rich text editor', 'Media upload', 'Scheduling', 'Analytics'],
    rating: 4.3,
    downloads: '620K',
  },
  {
    id: 'sheets',
    name: 'Sheets',
    category: 'Professional',
    description: 'A spreadsheet application',
    icon: '📊',
    default: true,
    features: ['Spreadsheets', 'Formulas', 'Charts', 'Collaboration', 'Export'],
    rating: 4.7,
    downloads: '4.1M',
  },
  {
    id: 'slides',
    name: 'Slides',
    category: 'Professional',
    description: 'A presentation application',
    icon: '🎯',
    default: true,
    features: ['Presentations', 'Templates', 'Animations', 'Sharing', 'Export'],
    rating: 4.6,
    downloads: '3.5M',
  },

  // Business Apps
  {
    id: 'calculator',
    name: 'Calculator',
    category: 'Business',
    description: 'A basic calculator',
    icon: '🧮',
    default: true,
    features: ['Basic math', 'Scientific mode', 'History', 'Currency conversion'],
    rating: 4.9,
    downloads: '12.3M',
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    category: 'Business',
    description: 'Buy and sell items',
    icon: '🛍️',
    default: true,
    features: ['Listings', 'Bidding', 'Payments', 'Reviews', 'Messaging'],
    rating: 4.5,
    downloads: '6.7M',
  },
  {
    id: 'bank',
    name: 'Bank',
    category: 'Business',
    description: 'Manage your finances',
    icon: '🏦',
    default: true,
    features: ['Accounts', 'Transfers', 'Bills', 'Investments', 'Security'],
    rating: 4.8,
    downloads: '9.2M',
  },
  {
    id: 'sales',
    name: 'Sales',
    category: 'Business',
    description: 'Track sales and revenue',
    icon: '📈',
    default: false,
    features: ['Sales tracking', 'Reports', 'Forecasting', 'Team management'],
    rating: 4.4,
    downloads: '450K',
  },
  {
    id: 'advertisement',
    name: 'Ads',
    category: 'Business',
    description: 'Manage advertisements',
    icon: '📢',
    default: true,
    features: ['Ad creation', 'Targeting', 'Analytics', 'Budget management'],
    rating: 4.3,
    downloads: '2.1M',
  },
  {
    id: 'shop-app',
    name: 'Shop',
    category: 'Business',
    description: 'An e-commerce storefront',
    icon: '🏪',
    default: true,
    features: ['Product catalog', 'Shopping cart', 'Checkout', 'Inventory', 'Orders'],
    rating: 4.6,
    downloads: '5.8M',
  },
  {
    id: 'pages',
    name: 'Pages',
    category: 'Business',
    description: 'Manage business pages',
    icon: '📄',
    default: true,
    features: ['Page creation', 'Branding', 'Analytics', 'Scheduling'],
    rating: 4.4,
    downloads: '1.9M',
  },
  {
    id: 'text',
    name: 'Text',
    category: 'Business',
    description: 'A simple text editor',
    icon: '📝',
    default: true,
    features: ['Text editing', 'Formatting', 'Saving', 'Search & replace'],
    rating: 4.5,
    downloads: '3.2M',
  },

  // Broadcast Apps
  {
    id: 'commercials',
    name: 'Commercials',
    category: 'Broadcast',
    description: 'View commercials',
    icon: '📺',
    default: false,
    features: ['Ad viewing', 'Recommendations', 'Favorites', 'Sharing'],
    rating: 3.8,
    downloads: '890K',
  },
  {
    id: 'channels',
    name: 'Channels',
    category: 'Broadcast',
    description: 'A feature-rich channel browser and player',
    icon: '📻',
    default: false,
    features: ['Channel browsing', 'Live streaming', 'DVR', 'Recommendations'],
    rating: 4.5,
    downloads: '3.4M',
  },
  {
    id: 'tv-show',
    name: 'TV Show',
    category: 'Broadcast',
    description: 'Watch TV shows',
    icon: '📹',
    default: true,
    features: ['Show library', 'Episodes', 'Watchlist', 'Recommendations'],
    rating: 4.6,
    downloads: '7.1M',
  },
  {
    id: 'radio-show',
    name: 'Radio Show',
    category: 'Broadcast',
    description: 'Listen to radio shows',
    icon: '🎙️',
    default: false,
    features: ['Radio stations', 'Podcasts', 'Recording', 'Favorites'],
    rating: 4.4,
    downloads: '2.3M',
  },
  {
    id: 'movies-app',
    name: 'Movies',
    category: 'Broadcast',
    description: 'Browse and watch movies',
    icon: '🎬',
    default: true,
    features: ['Movie library', 'Streaming', 'Ratings', 'Watchlist'],
    rating: 4.7,
    downloads: '8.5M',
  },
  {
    id: 'main-channel',
    name: 'Main Channel',
    category: 'Broadcast',
    description: 'The main broadcast channel',
    icon: '🎪',
    default: true,
    features: ['Live content', 'Archives', 'Chat', 'Notifications'],
    rating: 4.5,
    downloads: '4.2M',
  },
  {
    id: 'sub-main-channel',
    name: 'Sub Main',
    category: 'Broadcast',
    description: 'A secondary broadcast channel',
    icon: '🎭',
    default: false,
    features: ['Alternative content', 'Archives', 'Community'],
    rating: 4.2,
    downloads: '1.1M',
  },
  {
    id: 'his-main-channel',
    name: 'His Main',
    category: 'Broadcast',
    description: 'A personal broadcast channel',
    icon: '👨',
    default: false,
    features: ['Personal streams', 'Followers', 'Donations'],
    rating: 4.3,
    downloads: '890K',
  },
  {
    id: 'her-main-channel',
    name: 'Her Main',
    category: 'Broadcast',
    description: 'A personal broadcast channel',
    icon: '👩',
    default: false,
    features: ['Personal streams', 'Followers', 'Donations'],
    rating: 4.4,
    downloads: '1.2M',
  },
  {
    id: 'ai-movies',
    name: 'AI Movies',
    category: 'Broadcast',
    description: 'Generate and watch AI-created movies',
    icon: '🤖',
    default: true,
    features: ['AI generation', 'Customization', 'Sharing', 'Library'],
    rating: 4.3,
    downloads: '2.8M',
  },

  // Entertainment Apps
  {
    id: 'shows',
    name: 'Shows',
    category: 'Entertainment',
    description: 'Browse and watch shows',
    icon: '🎬',
    default: false,
    features: ['Show catalog', 'Episodes', 'Subtitles', 'Recommendations'],
    rating: 4.6,
    downloads: '5.3M',
  },
  {
    id: 'movies',
    name: 'Movies',
    category: 'Entertainment',
    description: 'A library of movies to watch',
    icon: '🎥',
    default: false,
    features: ['Movie library', 'Streaming', 'Ratings', 'Reviews'],
    rating: 4.7,
    downloads: '7.8M',
  },
  {
    id: 'theater',
    name: 'Theater',
    category: 'Entertainment',
    description: 'Information about theater shows',
    icon: '🎭',
    default: false,
    features: ['Show listings', 'Tickets', 'Reviews', 'Schedules'],
    rating: 4.5,
    downloads: '1.5M',
  },
  {
    id: 'audio',
    name: 'Audio',
    category: 'Entertainment',
    description: 'Listen to audio content',
    icon: '🔊',
    default: true,
    features: ['Audio library', 'Playlists', 'Equalizer', 'Sharing'],
    rating: 4.6,
    downloads: '4.2M',
  },
  {
    id: 'radio',
    name: 'AI Radio',
    category: 'Entertainment',
    description: 'An AI-powered radio station',
    icon: '📻',
    default: true,
    features: ['AI playlists', 'Personalization', 'Recommendations'],
    rating: 4.5,
    downloads: '3.1M',
  },
  {
    id: 'ent-news',
    name: 'News',
    category: 'Entertainment',
    description: 'Entertainment news',
    icon: '📰',
    default: true,
    features: ['News feed', 'Categories', 'Notifications', 'Sharing'],
    rating: 4.4,
    downloads: '2.9M',
  },
  {
    id: 'music',
    name: 'Music',
    category: 'Entertainment',
    description: 'Listen to your music library',
    icon: '🎵',
    default: true,
    features: ['Music library', 'Playlists', 'Streaming', 'Lyrics'],
    rating: 4.8,
    downloads: '9.5M',
  },
  {
    id: 'trailers',
    name: 'Trailers',
    category: 'Entertainment',
    description: 'Watch movie trailers',
    icon: '🎞️',
    default: false,
    features: ['Trailer library', 'Ratings', 'Sharing', 'Notifications'],
    rating: 4.3,
    downloads: '1.8M',
  },
  {
    id: 'sports',
    name: 'Sports',
    category: 'Entertainment',
    description: 'Sports news and scores',
    icon: '⚽',
    default: false,
    features: ['Live scores', 'News', 'Stats', 'Fantasy leagues'],
    rating: 4.6,
    downloads: '6.2M',
  },
  {
    id: 'tv-shows',
    name: 'TV Shows',
    category: 'Entertainment',
    description: 'Track and watch TV shows',
    icon: '📺',
    default: true,
    features: ['Show tracking', 'Episodes', 'Reminders', 'Recommendations'],
    rating: 4.7,
    downloads: '5.9M',
  },
  {
    id: '24-hours',
    name: '24 Hours',
    category: 'Entertainment',
    description: '24-hour content stream',
    icon: '⏰',
    default: false,
    features: ['Continuous streaming', 'Schedule', 'Archives'],
    rating: 4.2,
    downloads: '890K',
  },
  {
    id: 'overnight',
    name: 'Overnight',
    category: 'Entertainment',
    description: 'Content for late-night viewing',
    icon: '🌙',
    default: false,
    features: ['Night content', 'Curated playlists', 'Mood selection'],
    rating: 4.1,
    downloads: '650K',
  },
  {
    id: 'challenges',
    name: 'Challenges',
    category: 'Entertainment',
    description: 'Participate in challenges',
    icon: '🏆',
    default: false,
    features: ['Challenge listings', 'Leaderboards', 'Rewards', 'Sharing'],
    rating: 4.4,
    downloads: '2.3M',
  },
  {
    id: 'watch',
    name: 'Watch',
    category: 'Entertainment',
    description: 'A simple video watching app',
    icon: '👀',
    default: false,
    features: ['Video playback', 'Playlists', 'Sharing', 'History'],
    rating: 4.3,
    downloads: '1.2M',
  },
  {
    id: 'live-stream',
    name: 'Live Stream',
    category: 'Entertainment',
    description: 'Watch live streams',
    icon: '🔴',
    default: false,
    features: ['Live streams', 'Chat', 'Donations', 'Recording'],
    rating: 4.5,
    downloads: '4.1M',
  },
  {
    id: 'travel',
    name: 'Travel',
    category: 'Entertainment',
    description: 'Travel vlogs and guides',
    icon: '✈️',
    default: false,
    features: ['Travel guides', 'Vlogs', 'Recommendations', 'Bookings'],
    rating: 4.6,
    downloads: '3.2M',
  },
  {
    id: 'models',
    name: 'Models',
    category: 'Entertainment',
    description: 'Information about models',
    icon: '👗',
    default: false,
    features: ['Model profiles', 'Portfolios', 'Bookings', 'Messaging'],
    rating: 4.2,
    downloads: '1.5M',
  },
  {
    id: 'fashion',
    name: 'Fashion',
    category: 'Entertainment',
    description: 'Fashion news and trends',
    icon: '👠',
    default: false,
    features: ['Trends', 'Collections', 'Shopping', 'Inspiration'],
    rating: 4.5,
    downloads: '3.8M',
  },
  {
    id: 'stage',
    name: 'Stage',
    category: 'Entertainment',
    description: 'Information about stage performances',
    icon: '🎪',
    default: false,
    features: ['Performance listings', 'Tickets', 'Reviews', 'Schedules'],
    rating: 4.4,
    downloads: '1.1M',
  },
  {
    id: 'magazine',
    name: 'Magazine',
    category: 'Entertainment',
    description: 'Read digital magazines',
    icon: '📖',
    default: false,
    features: ['Magazine library', 'Subscriptions', 'Offline reading'],
    rating: 4.3,
    downloads: '2.1M',
  },
  {
    id: 'ent-online',
    name: 'Online',
    category: 'Entertainment',
    description: 'Online entertainment content',
    icon: '💻',
    default: false,
    features: ['Online content', 'Streaming', 'Communities'],
    rating: 4.2,
    downloads: '1.9M',
  },
  {
    id: 'matt-grosso-show',
    name: 'MGS Studios',
    category: 'Entertainment',
    description: 'The official app for Matt Grosso Show Studios',
    icon: '🎬',
    default: true,
    features: ['Show content', 'Behind the scenes', 'Merchandise', 'Community'],
    rating: 4.7,
    downloads: '2.5M',
  },

  // Library Apps
  {
    id: 'media',
    name: 'Media',
    category: 'Library',
    description: 'A library of all your media',
    icon: '📚',
    default: true,
    features: ['Media organization', 'Search', 'Tagging', 'Sharing'],
    rating: 4.6,
    downloads: '4.3M',
  },
  {
    id: 'media-explorer',
    name: 'Media Explorer',
    category: 'Library',
    description: 'Explore your media files',
    icon: '🔍',
    default: true,
    features: ['File browsing', 'Preview', 'Metadata', 'Batch operations'],
    rating: 4.5,
    downloads: '2.8M',
  },
  {
    id: 'stories',
    name: 'Stories',
    category: 'Library',
    description: 'Read and write stories',
    icon: '📖',
    default: true,
    features: ['Story writing', 'Publishing', 'Reading', 'Community'],
    rating: 4.6,
    downloads: '3.5M',
  },
  {
    id: 'photo-lib',
    name: 'Photo',
    category: 'Library',
    description: 'Your personal photo library',
    icon: '🖼️',
    default: true,
    features: ['Photo organization', 'Editing', 'Sharing', 'Albums'],
    rating: 4.7,
    downloads: '6.9M',
  },
  {
    id: 'videos',
    name: 'Videos',
    category: 'Library',
    description: 'Browse and play local video files',
    icon: '🎥',
    default: true,
    features: ['Video playback', 'Playlists', 'Subtitles', 'Sharing'],
    rating: 4.6,
    downloads: '5.2M',
  },
  {
    id: 'music-player',
    name: 'Music',
    category: 'Library',
    description: 'A simple and elegant music player',
    icon: '🎶',
    default: true,
    features: ['Music playback', 'Playlists', 'Equalizer', 'Lyrics'],
    rating: 4.8,
    downloads: '7.1M',
  },
  {
    id: 'live',
    name: 'Live',
    category: 'Library',
    description: 'Access live content',
    icon: '🔴',
    default: true,
    features: ['Live streams', 'Notifications', 'Chat', 'Recording'],
    rating: 4.5,
    downloads: '3.2M',
  },
  {
    id: 'camera',
    name: 'Camera',
    category: 'Library',
    description: 'A simple camera application',
    icon: '📷',
    default: true,
    features: ['Photo capture', 'Video recording', 'Filters', 'Editing'],
    rating: 4.7,
    downloads: '8.3M',
  },
  {
    id: 'recorder',
    name: 'Recorder',
    category: 'Library',
    description: 'Record audio notes',
    icon: '🎙️',
    default: true,
    features: ['Audio recording', 'Transcription', 'Organization', 'Sharing'],
    rating: 4.6,
    downloads: '2.9M',
  },

  // Health Apps
  {
    id: 'health',
    name: 'Health',
    category: 'Health',
    description: 'Monitor your health',
    icon: '❤️',
    default: false,
    features: ['Health tracking', 'Vitals', 'Goals', 'Analytics'],
    rating: 4.6,
    downloads: '5.1M',
  },
  {
    id: 'hospital',
    name: 'Hospital',
    category: 'Health',
    description: 'A hospital management application',
    icon: '🏥',
    default: false,
    features: ['Patient records', 'Appointments', 'Billing', 'Staff management'],
    rating: 4.5,
    downloads: '1.8M',
  },
  {
    id: 'treatment',
    name: 'Treatment',
    category: 'Health',
    description: 'Track medical treatments',
    icon: '💊',
    default: false,
    features: ['Treatment tracking', 'Medications', 'Reminders', 'Progress'],
    rating: 4.4,
    downloads: '1.2M',
  },
  {
    id: 'experiments',
    name: 'Experiments',
    category: 'Health',
    description: 'Log and track experiments',
    icon: '🧪',
    default: false,
    features: ['Experiment logging', 'Data analysis', 'Sharing', 'Collaboration'],
    rating: 4.3,
    downloads: '650K',
  },
  {
    id: 'dr',
    name: 'Dr',
    category: 'Health',
    description: 'Doctor profiles and information',
    icon: '👨‍⚕️',
    default: false,
    features: ['Doctor directory', 'Appointments', 'Reviews', 'Messaging'],
    rating: 4.6,
    downloads: '3.4M',
  },
  {
    id: 'nurse',
    name: 'Nurse',
    category: 'Health',
    description: 'Nurse profiles and information',
    icon: '👩‍⚕️',
    default: false,
    features: ['Nurse directory', 'Scheduling', 'Reviews', 'Messaging'],
    rating: 4.5,
    downloads: '1.9M',
  },
  {
    id: 'school',
    name: 'School',
    category: 'Health',
    description: 'Access school-related information',
    icon: '🎓',
    default: false,
    features: ['Course listings', 'Enrollment', 'Grades', 'Resources'],
    rating: 4.5,
    downloads: '2.3M',
  },
  {
    id: 'test-health',
    name: 'Test',
    category: 'Health',
    description: 'View test results',
    icon: '📋',
    default: false,
    features: ['Test results', 'History', 'Analysis', 'Sharing'],
    rating: 4.4,
    downloads: '1.1M',
  },
  {
    id: 'aids',
    name: 'Aids',
    category: 'Health',
    description: 'Information about medical aids',
    icon: '🦽',
    default: false,
    features: ['Aid directory', 'Resources', 'Support groups', 'Information'],
    rating: 4.3,
    downloads: '890K',
  },
  {
    id: 'manager',
    name: 'Manager',
    category: 'Health',
    description: 'Management tools',
    icon: '📊',
    default: false,
    features: ['Task management', 'Scheduling', 'Analytics', 'Reporting'],
    rating: 4.4,
    downloads: '1.5M',
  },
  {
    id: 'adult',
    name: 'Adult',
    category: 'Health',
    description: 'Adult health information',
    icon: '👨',
    default: false,
    features: ['Health articles', 'Wellness tips', 'Community', 'Resources'],
    rating: 4.3,
    downloads: '2.1M',
  },
  {
    id: 'kids',
    name: 'Kids',
    category: 'Health',
    description: 'Pediatric health information',
    icon: '👶',
    default: false,
    features: ['Growth tracking', 'Vaccination records', 'Tips', 'Community'],
    rating: 4.6,
    downloads: '3.2M',
  },
  {
    id: 'family-health',
    name: 'Family',
    category: 'Health',
    description: 'Family health management',
    icon: '👨‍👩‍👧‍👦',
    default: false,
    features: ['Family profiles', 'Health tracking', 'Sharing', 'Reminders'],
    rating: 4.5,
    downloads: '2.8M',
  },
  {
    id: 'blood',
    name: 'Blood',
    category: 'Health',
    description: 'Blood work and analysis',
    icon: '🩸',
    default: false,
    features: ['Blood test results', 'Analysis', 'Trends', 'Sharing'],
    rating: 4.4,
    downloads: '1.3M',
  },
  {
    id: 'teeth',
    name: 'Teeth',
    category: 'Health',
    description: 'Dental health information',
    icon: '😁',
    default: false,
    features: ['Dental records', 'Appointments', 'Care tips', 'Community'],
    rating: 4.5,
    downloads: '1.8M',
  },
  {
    id: 'hair',
    name: 'Hair',
    category: 'Health',
    description: 'Hair care and health',
    icon: '💇',
    default: false,
    features: ['Hair care tips', 'Product reviews', 'Styling', 'Community'],
    rating: 4.3,
    downloads: '1.5M',
  },
  {
    id: 'skin',
    name: 'Skin',
    category: 'Health',
    description: 'Skin care and health',
    icon: '🧴',
    default: false,
    features: ['Skincare tips', 'Product reviews', 'Tracking', 'Community'],
    rating: 4.6,
    downloads: '2.9M',
  },
  {
    id: 'bone',
    name: 'Bone',
    category: 'Health',
    description: 'Orthopedic information',
    icon: '🦴',
    default: false,
    features: ['Orthopedic info', 'Exercises', 'Resources', 'Community'],
    rating: 4.4,
    downloads: '1.2M',
  },
  {
    id: 'tissue',
    name: 'Tissue',
    category: 'Health',
    description: 'Histology and tissue analysis',
    icon: '🔬',
    default: false,
    features: ['Tissue analysis', 'Research', 'Data sharing', 'Community'],
    rating: 4.2,
    downloads: '650K',
  },
  {
    id: 'mussels',
    name: 'Mussels',
    category: 'Health',
    description: 'Information about mussels (seafood)',
    icon: '🦪',
    default: false,
    features: ['Nutrition info', 'Recipes', 'Sourcing', 'Community'],
    rating: 4.1,
    downloads: '420K',
  },
  {
    id: 'cells',
    name: 'Cells',
    category: 'Health',
    description: 'Cellular biology information',
    icon: '🧬',
    default: false,
    features: ['Biology info', 'Research', 'Visualization', 'Community'],
    rating: 4.3,
    downloads: '890K',
  },

  // Medical Apps
  {
    id: 'diseases',
    name: 'Diseases',
    category: 'Medical',
    description: 'Information about various diseases',
    icon: '🦠',
    default: false,
    features: ['Disease info', 'Symptoms', 'Prevention', 'Resources'],
    rating: 4.5,
    downloads: '2.8M',
  },
  {
    id: 'viruses',
    name: 'Viruses',
    category: 'Medical',
    description: 'Information about viruses',
    icon: '🧫',
    default: false,
    features: ['Virus info', 'Tracking', 'Prevention', 'Resources'],
    rating: 4.4,
    downloads: '1.9M',
  },
  {
    id: 'test-medical',
    name: 'Test',
    category: 'Medical',
    description: 'Medical testing information',
    icon: '🧬',
    default: false,
    features: ['Test info', 'Booking', 'Results', 'Sharing'],
    rating: 4.5,
    downloads: '1.6M',
  },
  {
    id: 'medical',
    name: 'Medical',
    category: 'Medical',
    description: 'General medical information',
    icon: '⚕️',
    default: false,
    features: ['Medical info', 'Resources', 'Community', 'Support'],
    rating: 4.6,
    downloads: '3.5M',
  },
  {
    id: 'insurances',
    name: 'Insurances',
    category: 'Medical',
    description: 'Manage medical insurance',
    icon: '🛡️',
    default: false,
    features: ['Policy management', 'Claims', 'Billing', 'Support'],
    rating: 4.4,
    downloads: '1.8M',
  },
  {
    id: 'outbreaks',
    name: 'Outbreaks',
    category: 'Medical',
    description: 'Track disease outbreaks',
    icon: '📊',
    default: false,
    features: ['Outbreak tracking', 'Alerts', 'Maps', 'Statistics'],
    rating: 4.3,
    downloads: '1.1M',
  },
  {
    id: 'fire',
    name: 'Fire',
    category: 'Medical',
    description: 'Fire safety and response',
    icon: '🔥',
    default: false,
    features: ['Safety info', 'Emergency response', 'Prevention', 'Resources'],
    rating: 4.5,
    downloads: '1.5M',
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Medical',
    description: 'Water safety and quality',
    icon: '💧',
    default: false,
    features: ['Water quality', 'Safety info', 'Testing', 'Resources'],
    rating: 4.4,
    downloads: '1.2M',
  },
  {
    id: 'air',
    name: 'Air',
    category: 'Medical',
    description: 'Air quality and safety',
    icon: '💨',
    default: false,
    features: ['Air quality', 'Alerts', 'Health tips', 'Resources'],
    rating: 4.5,
    downloads: '1.8M',
  },
  {
    id: 'rescues',
    name: 'Rescues',
    category: 'Medical',
    description: 'Coordinate and manage rescue operations',
    icon: '🚁',
    default: false,
    features: ['Rescue coordination', 'Alerts', 'Resources', 'Community'],
    rating: 4.6,
    downloads: '2.1M',
  },

  // Law Apps
  {
    id: 'judge',
    name: 'Judge',
    category: 'Law',
    description: 'Legal information from a judge perspective',
    icon: '⚖️',
    default: false,
    features: ['Legal info', 'Case law', 'Resources', 'Community'],
    rating: 4.5,
    downloads: '1.3M',
  },
  {
    id: 'lawyers',
    name: 'Lawyers',
    category: 'Law',
    description: 'Directory of lawyers',
    icon: '👨‍⚖️',
    default: false,
    features: ['Lawyer directory', 'Reviews', 'Booking', 'Messaging'],
    rating: 4.6,
    downloads: '2.5M',
  },
  {
    id: 'law-school',
    name: 'Law School',
    category: 'Law',
    description: 'Information about law school',
    icon: '📚',
    default: false,
    features: ['School info', 'Courses', 'Admissions', 'Resources'],
    rating: 4.5,
    downloads: '1.1M',
  },
  {
    id: 'police',
    name: 'Police',
    category: 'Law',
    description: 'Police department information',
    icon: '🚔',
    default: false,
    features: ['Department info', 'Reports', 'Alerts', 'Community'],
    rating: 4.4,
    downloads: '1.9M',
  },
  {
    id: 'politicians',
    name: 'Politicians',
    category: 'Law',
    description: 'Information about politicians',
    icon: '🏛️',
    default: false,
    features: ['Politician profiles', 'Voting records', 'Contact', 'News'],
    rating: 4.3,
    downloads: '1.4M',
  },
  {
    id: 'mayor',
    name: 'Mayor',
    category: 'Law',
    description: 'Information about the mayor office',
    icon: '👨‍💼',
    default: false,
    features: ['Office info', 'Services', 'Events', 'Contact'],
    rating: 4.2,
    downloads: '890K',
  },
  {
    id: 'president',
    name: 'President',
    category: 'Law',
    description: 'Information about the president office',
    icon: '🏛️',
    default: false,
    features: ['Office info', 'Speeches', 'News', 'Resources'],
    rating: 4.3,
    downloads: '1.2M',
  },
  {
    id: 'government',
    name: 'Government',
    category: 'Law & Government',
    description: 'Government services and information',
    icon: '🏢',
    default: false,
    features: ['Services', 'Information', 'Permits', 'Support'],
    rating: 4.4,
    downloads: '1.6M',
  },

  // Home Apps
  {
    id: 'homes',
    name: 'Homes',
    category: 'Home',
    description: 'Manage home-related tasks',
    icon: '🏠',
    default: false,
    features: ['Task management', 'Checklists', 'Scheduling', 'Sharing'],
    rating: 4.5,
    downloads: '2.2M',
  },
  {
    id: 'camping',
    name: 'Camping',
    category: 'Home',
    description: 'Plan camping trips',
    icon: '⛺',
    default: false,
    features: ['Trip planning', 'Location finder', 'Packing list', 'Community'],
    rating: 4.6,
    downloads: '1.8M',
  },
  {
    id: 'hiking',
    name: 'Hiking',
    category: 'Home',
    description: 'Find hiking trails',
    icon: '🥾',
    default: false,
    features: ['Trail finder', 'Maps', 'Reviews', 'Tracking'],
    rating: 4.7,
    downloads: '2.5M',
  },
  {
    id: 'fishing',
    name: 'Fishing',
    category: 'Home',
    description: 'Fishing information and logs',
    icon: '🎣',
    default: false,
    features: ['Spot finder', 'Logs', 'Tips', 'Community'],
    rating: 4.5,
    downloads: '1.5M',
  },
  {
    id: 'trailing',
    name: 'Trailing',
    category: 'Home',
    description: 'Track your trails',
    icon: '🗺️',
    default: false,
    features: ['Trail tracking', 'Maps', 'Statistics', 'Sharing'],
    rating: 4.4,
    downloads: '1.1M',
  },
  {
    id: 'home-friends',
    name: 'Friends',
    category: 'Home',
    description: 'Connect with friends at home',
    icon: '👫',
    default: false,
    features: ['Friend network', 'Events', 'Messaging', 'Community'],
    rating: 4.5,
    downloads: '1.9M',
  },
  {
    id: 'home-family',
    name: 'Family',
    category: 'Home',
    description: 'Family organization tools',
    icon: '👨‍👩‍👧‍👦',
    default: false,
    features: ['Family calendar', 'Chores', 'Budget', 'Messaging'],
    rating: 4.6,
    downloads: '2.3M',
  },
  {
    id: 'home-kids',
    name: 'Kids',
    category: 'Home',
    description: 'Activities and tools for kids',
    icon: '🧒',
    default: false,
    features: ['Activities', 'Learning', 'Games', 'Parental controls'],
    rating: 4.6,
    downloads: '2.8M',
  },
  {
    id: 'repairs',
    name: 'Repairs',
    category: 'Home',
    description: 'Track home repairs',
    icon: '🔧',
    default: false,
    features: ['Repair tracking', 'Contractor finder', 'Quotes', 'History'],
    rating: 4.4,
    downloads: '1.3M',
  },
  {
    id: 'supplies',
    name: 'Supplies',
    category: 'Home',
    description: 'Manage household supplies',
    icon: '🛒',
    default: false,
    features: ['Inventory', 'Shopping list', 'Reordering', 'Sharing'],
    rating: 4.5,
    downloads: '1.6M',
  },
  {
    id: 'money',
    name: 'Money',
    category: 'Home',
    description: 'Personal finance management',
    icon: '💰',
    default: false,
    features: ['Budget tracking', 'Expenses', 'Savings', 'Analytics'],
    rating: 4.7,
    downloads: '3.9M',
  },
  {
    id: 'downloads',
    name: 'Downloads',
    category: 'Home',
    description: 'View and manage downloaded files',
    icon: '⬇️',
    default: true,
    features: ['File management', 'Organization', 'Sharing', 'Cleanup'],
    rating: 4.5,
    downloads: '2.1M',
  },

  // Life Apps
  {
    id: 'the-fam',
    name: 'The Fam',
    category: 'Life',
    description: 'Family organization and communication',
    icon: '👨‍👩‍👧‍👦',
    default: false,
    features: ['Family chat', 'Calendar', 'Tasks', 'Photo sharing'],
    rating: 4.6,
    downloads: '2.4M',
  },
  {
    id: 'plants',
    name: 'Plants',
    category: 'Life',
    description: 'Care for your virtual plants',
    icon: '🌱',
    default: false,
    features: ['Plant care', 'Reminders', 'Community', 'Achievements'],
    rating: 4.5,
    downloads: '1.8M',
  },
  {
    id: 'animals',
    name: 'Animals',
    category: 'Life',
    description: 'Information about animals',
    icon: '🦁',
    default: false,
    features: ['Animal info', 'Encyclopedia', 'Community', 'Resources'],
    rating: 4.6,
    downloads: '2.2M',
  },
  {
    id: 'people',
    name: 'People',
    category: 'Life',
    description: 'Manage information about people',
    icon: '👥',
    default: false,
    features: ['Contact management', 'Profiles', 'Networking', 'Messaging'],
    rating: 4.4,
    downloads: '1.5M',
  },
  {
    id: 'props',
    name: 'Props',
    category: 'Life',
    description: 'Manage props for projects',
    icon: '🎭',
    default: false,
    features: ['Prop inventory', 'Tracking', 'Rental', 'Community'],
    rating: 4.3,
    downloads: '890K',
  },
  {
    id: 'party',
    name: 'Party',
    category: 'Life',
    description: 'Plan and manage parties',
    icon: '🎉',
    default: false,
    features: ['Event planning', 'Guest list', 'Budget', 'Reminders'],
    rating: 4.5,
    downloads: '1.9M',
  },
  {
    id: 'dates',
    name: 'Dates',
    category: 'Life',
    description: 'Keep track of important dates',
    icon: '📅',
    default: false,
    features: ['Date tracking', 'Reminders', 'Sharing', 'Calendar'],
    rating: 4.4,
    downloads: '1.2M',
  },
  {
    id: 'parks',
    name: 'Parks',
    category: 'Life',
    description: 'Information about local parks',
    icon: '🌳',
    default: false,
    features: ['Park finder', 'Maps', 'Reviews', 'Events'],
    rating: 4.5,
    downloads: '1.6M',
  },
  {
    id: 'recreations',
    name: 'Recreations',
    category: 'Life',
    description: 'Find recreational activities',
    icon: '⚽',
    default: false,
    features: ['Activity finder', 'Booking', 'Reviews', 'Community'],
    rating: 4.5,
    downloads: '1.8M',
  },
  {
    id: 'makeup',
    name: 'Makeup',
    category: 'Life',
    description: 'Makeup tutorials and looks',
    icon: '💄',
    default: false,
    features: ['Tutorials', 'Product reviews', 'Looks', 'Community'],
    rating: 4.6,
    downloads: '2.3M',
  },
  {
    id: 'costume-life',
    name: 'Costume',
    category: 'Life',
    description: 'Manage your costumes',
    icon: '🎭',
    default: false,
    features: ['Costume catalog', 'Tracking', 'Rental', 'Community'],
    rating: 4.4,
    downloads: '1.1M',
  },
  {
    id: 'parade',
    name: 'Parade',
    category: 'Life',
    description: 'Information about parades',
    icon: '🎊',
    default: false,
    features: ['Parade listings', 'Maps', 'Events', 'Community'],
    rating: 4.3,
    downloads: '890K',
  },

  // Law & Government Apps
  {
    id: 'gov-law',
    name: 'Law',
    category: 'Law & Government',
    description: 'Legal resources',
    icon: '⚖️',
    default: false,
    features: ['Legal resources', 'Case law', 'Forms', 'Community'],
    rating: 4.5,
    downloads: '1.4M',
  },
  {
    id: 'gov-police',
    name: 'Police',
    category: 'Law & Government',
    description: 'Police department resources',
    icon: '🚔',
    default: false,
    features: ['Department info', 'Reports', 'Resources', 'Community'],
    rating: 4.4,
    downloads: '1.2M',
  },
  {
    id: 'gov-lawyer',
    name: 'Lawyer',
    category: 'Law & Government',
    description: 'Lawyer directory',
    icon: '👨‍⚖️',
    default: false,
    features: ['Lawyer finder', 'Reviews', 'Booking', 'Messaging'],
    rating: 4.6,
    downloads: '1.8M',
  },
  {
    id: 'gov-judge',
    name: 'Judge',
    category: 'Law & Government',
    description: 'Information about judges',
    icon: '⚖️',
    default: false,
    features: ['Judge profiles', 'Case info', 'Resources', 'Community'],
    rating: 4.4,
    downloads: '1.0M',
  },
  {
    id: 'gov-politician',
    name: 'Politician',
    category: 'Law & Government',
    description: 'Politician directory',
    icon: '🏛️',
    default: false,
    features: ['Politician profiles', 'Voting records', 'Contact', 'News'],
    rating: 4.3,
    downloads: '1.3M',
  },
  {
    id: 'gov-president',
    name: 'President',
    category: 'Law & Government',
    description: 'Presidential information',
    icon: '🏛️',
    default: false,
    features: ['President info', 'Speeches', 'News', 'Resources'],
    rating: 4.3,
    downloads: '1.1M',
  },
  {
    id: 'gov-governor',
    name: 'Governor',
    category: 'Law & Government',
    description: 'Governor information',
    icon: '👨‍💼',
    default: false,
    features: ['Governor info', 'Policies', 'News', 'Resources'],
    rating: 4.2,
    downloads: '890K',
  },
  {
    id: 'gov-election',
    name: 'Election',
    category: 'Law & Government',
    description: 'Election information',
    icon: '🗳️',
    default: false,
    features: ['Election info', 'Candidates', 'Polling', 'Resources'],
    rating: 4.4,
    downloads: '1.5M',
  },
  {
    id: 'gov-voting',
    name: 'Voting',
    category: 'Law & Government',
    description: 'Voter information',
    icon: '✅',
    default: false,
    features: ['Voter registration', 'Polling locations', 'Info', 'Resources'],
    rating: 4.5,
    downloads: '1.7M',
  },
  {
    id: 'gov-sponsors',
    name: 'Sponsors',
    category: 'Law & Government',
    description: 'Government sponsors',
    icon: '🤝',
    default: false,
    features: ['Sponsor directory', 'Programs', 'Applications', 'Support'],
    rating: 4.3,
    downloads: '890K',
  },
  {
    id: 'gov-class',
    name: 'Class',
    category: 'Law & Government',
    description: 'Civics classes',
    icon: '📚',
    default: false,
    features: ['Class listings', 'Enrollment', 'Materials', 'Community'],
    rating: 4.5,
    downloads: '1.2M',
  },

  // Exploration Apps
  {
    id: 'exploring',
    name: 'Exploring',
    category: 'Exploration',
    description: 'Explore the world',
    icon: '🌍',
    default: false,
    features: ['Destination finder', 'Maps', 'Reviews', 'Planning'],
    rating: 4.6,
    downloads: '2.3M',
  },
  {
    id: 'adventure',
    name: 'Adventure',
    category: 'Exploration',
    description: 'Plan your next adventure',
    icon: '🧗',
    default: false,
    features: ['Adventure planning', 'Guides', 'Community', 'Booking'],
    rating: 4.7,
    downloads: '2.8M',
  },
  {
    id: 'abandoned-exp',
    name: 'Abandoned',
    category: 'Exploration',
    description: 'Explore abandoned places',
    icon: '🏚️',
    default: false,
    features: ['Location finder', 'Maps', 'Community', 'Safety tips'],
    rating: 4.4,
    downloads: '1.5M',
  },
  {
    id: 'ghost-hunting',
    name: 'Ghost Hunting',
    category: 'Exploration',
    description: 'Tools for ghost hunting',
    icon: '👻',
    default: false,
    features: ['Ghost hunting tools', 'Hotspot maps', 'Community', 'Logging'],
    rating: 4.2,
    downloads: '890K',
  },
  {
    id: 'hauntings',
    name: 'Hauntings',
    category: 'Exploration',
    description: 'Information about haunted places',
    icon: '🏰',
    default: false,
    features: ['Haunted locations', 'Stories', 'Maps', 'Community'],
    rating: 4.3,
    downloads: '1.2M',
  },
  {
    id: 'places',
    name: 'Places',
    category: 'Exploration',
    description: 'Discover interesting places',
    icon: '📍',
    default: false,
    features: ['Place discovery', 'Maps', 'Reviews', 'Sharing'],
    rating: 4.6,
    downloads: '2.1M',
  },
];

export default function ComprehensiveAppStore() {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');

  const categories = Array.from(new Set(APPS_DATABASE.map(app => app.category))).sort();

  const filteredApps = useMemo(() => {
    return APPS_DATABASE.filter(app => {
      const matchesSearch = app.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                           app.description.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = !selectedCategory || app.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchQuery, selectedCategory]);

  return (
    <div className="w-full h-full flex flex-col bg-background">
      {/* Header */}
      <div className="border-b border-border p-4 bg-card space-y-3">
        <h2 className="text-lg font-bold">🏪 App Store</h2>

        {/* Search Bar */}
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-foreground/50" />
          <input
            type="text"
            placeholder="Search apps..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-8 py-2 bg-background border border-border rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-accent"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-foreground/50 hover:text-foreground"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>

        {/* Category Filter */}
        <div className="flex gap-2 overflow-x-auto pb-2">
          <Button
            onClick={() => setSelectedCategory(null)}
            variant={selectedCategory === null ? 'default' : 'outline'}
            size="sm"
            className="whitespace-nowrap"
          >
            All
          </Button>
          {categories.map(category => (
            <Button
              key={category}
              onClick={() => setSelectedCategory(category)}
              variant={selectedCategory === category ? 'default' : 'outline'}
              size="sm"
              className="whitespace-nowrap"
            >
              {category}
            </Button>
          ))}
        </div>
      </div>

      {/* Apps Grid/List */}
      <div className="flex-1 overflow-y-auto p-4">
        {filteredApps.length === 0 ? (
          <div className="flex items-center justify-center h-full text-foreground/60">
            <p>No apps found matching your search.</p>
          </div>
        ) : (
          <div className={viewMode === 'grid' ? 'grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4' : 'space-y-2'}>
            {filteredApps.map(app => (
              <div
                key={app.id}
                className={`bg-card border border-border rounded-lg p-4 hover:border-accent hover:bg-accent/5 transition-all cursor-pointer group ${
                  viewMode === 'list' ? 'flex items-center gap-4' : ''
                }`}
              >
                <div className={viewMode === 'list' ? '' : 'text-center'}>
                  <div className={`text-4xl mb-2 ${viewMode === 'list' ? 'text-3xl' : ''}`}>
                    {app.icon}
                  </div>
                  <h3 className="font-semibold text-sm truncate">{app.name}</h3>
                  <p className="text-xs text-foreground/60 line-clamp-2 mb-2">{app.description}</p>
                  
                  {/* Features */}
                  <div className="text-xs text-foreground/50 mb-2 line-clamp-2">
                    {app.features.join(', ')}
                  </div>

                  {/* Rating and Downloads */}
                  <div className="flex items-center justify-between text-xs text-foreground/60 mb-2">
                    <span>⭐ {app.rating}</span>
                    <span>📥 {app.downloads}</span>
                  </div>

                  {/* Install Button */}
                  <Button
                    size="sm"
                    className="w-full group-hover:bg-accent group-hover:text-accent-foreground"
                  >
                    <Download className="w-3 h-3 mr-1" />
                    Install
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Footer Stats */}
      <div className="border-t border-border px-4 py-2 bg-card text-xs text-foreground/60">
        Showing {filteredApps.length} of {APPS_DATABASE.length} apps
      </div>
    </div>
  );
}
